#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
#------------------------------------------------------------------------------

( cd airfoil_snappyHexMesh && cleanCase )

#( cd airfoil_simpleFoam && cleanCase0 )
#( cd airfoil_pimpleFoam && cleanCase0 )

#------------------------------------------------------------------------------
