#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

#runApplication surfaceFeatureExtract
#runApplication blockMesh
#runApplication decomposePar
#runApplication snappyHexMesh -overwrite
#runApplication reconstructParMesh
#rm -r processor*
runApplication decomposePar
runParallel $(getApplication)
runApplication reconstructPar
#------------------------------------------------------------------------------
