#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
#------------------------------------------------------------------------------

cleanCase0
rm job*
cp -r ../laminarPipe1/0 .
#cp -r ../laminarSnappy/constant/polyMesh ./constant
touch f.foam
#------------------------------------------------------------------------------
